language: node_js

node_js:
- 6.10.3

env:
  global:
  - GIT_NAME=Travis CI
  - GIT_EMAIL=grailians@gmail.com
  - GITHUB_REPO=codehangar/reqlpro
  - GIT_SOURCE=_docpress

before_install:
- sudo apt-get update
- sudo apt-get install libsecret-1-dev

cache:
  directories:
  - node_modules

script:
- npm run test-coverage

after_success:
- ./node_modules/.bin/docpress build
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then ./node_modules/.bin/git-update-ghpages -e; fi

after_script:
- npm install coveralls@2 && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls

notifications:
  slack:
    rooms:
      secure: OkBl59oPrlvyOShUk0p4t/b4DMR5X1c7/17iBVe12PXibK14hVxJJ1Sl5YDTCN3fH+d4z5xraovq1ejK43WJKx6r+Kxpc8M4BllbU9X8fAHau1+1sGoNNmrSSH294VaeCtoGl3qFOUur1W5DTjXwqZR+s7tNYWeG84FBMjssLvVr4wCdgaMXP+6E01T63XV5VgUJDCL4NLbuHVOJpmCd5NG3eWeHDtL7lwu+CZxHtHnTgSkWZ80dgFUR87IuieyjgFN5X1Du4GSjXNnJbnRf1iXrbNku8qojOM9Tmb2dPbfJUNEBlJ7NlL4jtlXYyOZ4oYq0kFShAyxjskCCWBJUMSh+HT1soR1tOd9zywLSFYrgfwR0G1qH2aiTux0Qfa5D4ipkg7p7F61g8yVIExqsJEw+uzbQ5S/HwFifywzfqpHmKcfNGNg+s6jqygVQQ56+nBGKMiGvpj6qe1UoeY3DxY9SCVcd3R5skLHUQyaRKU3aujnzPwBPgv+ezUN3zq015Jak1XFnfyYlWNLW7zLadkth17IRurikgGSF5tZJDuDeJwNwJgj3arY22d5F1WkBHy1AW5f6TwI8GlAjToT7t4BJQekm3Be4dx9no2odvrnd71c7wEBr+aONeMkkiRP4LxHUKh4m3dhheUtZ+wa+eX/PS+3YeIBOT6yp+Fnh6+w=
