language: node_js
node_js:
  - "6.10.3"
before_install:
  - sudo apt-get update
  - sudo apt-get install libsecret-1-dev
cache:
  directories:
    - "node_modules"
script:
  - "npm run test-coverage"
after_script:
  - "npm install coveralls@2 && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
sudo: false
